/*
 * This file is generated by jOOQ.
 */
package com.ethan.generator.tables.daos;


import com.ethan.generator.tables.BookToBookStore;
import com.ethan.generator.tables.records.BookToBookStoreRecord;

import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.Record2;
import org.jooq.impl.DAOImpl;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Repository;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Repository
public class BookToBookStoreDao extends DAOImpl<BookToBookStoreRecord, com.ethan.generator.tables.pojos.BookToBookStore, Record2<String, Integer>> {

    /**
     * Create a new BookToBookStoreDao without any configuration
     */
    public BookToBookStoreDao() {
        super(BookToBookStore.BOOK_TO_BOOK_STORE, com.ethan.generator.tables.pojos.BookToBookStore.class);
    }

    /**
     * Create a new BookToBookStoreDao with an attached configuration
     */
    @Autowired
    public BookToBookStoreDao(Configuration configuration) {
        super(BookToBookStore.BOOK_TO_BOOK_STORE, com.ethan.generator.tables.pojos.BookToBookStore.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Record2<String, Integer> getId(com.ethan.generator.tables.pojos.BookToBookStore object) {
        return compositeKeyRecord(object.getName(), object.getBookId());
    }

    /**
     * Fetch records that have <code>name IN (values)</code>
     */
    public List<com.ethan.generator.tables.pojos.BookToBookStore> fetchByName(String... values) {
        return fetch(BookToBookStore.BOOK_TO_BOOK_STORE.NAME, values);
    }

    /**
     * Fetch records that have <code>book_id IN (values)</code>
     */
    public List<com.ethan.generator.tables.pojos.BookToBookStore> fetchByBookId(Integer... values) {
        return fetch(BookToBookStore.BOOK_TO_BOOK_STORE.BOOK_ID, values);
    }

    /**
     * Fetch records that have <code>stock IN (values)</code>
     */
    public List<com.ethan.generator.tables.pojos.BookToBookStore> fetchByStock(Integer... values) {
        return fetch(BookToBookStore.BOOK_TO_BOOK_STORE.STOCK, values);
    }
}
