/*
 * This file is generated by jOOQ.
 */
package com.ethan.generator;


import com.ethan.generator.tables.Author;
import com.ethan.generator.tables.Book;
import com.ethan.generator.tables.BookStore;
import com.ethan.generator.tables.BookToBookStore;
import com.ethan.generator.tables.Department;
import com.ethan.generator.tables.Language;
import com.ethan.generator.tables.User;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Jooq extends SchemaImpl {

    private static final long serialVersionUID = -608605076;

    /**
     * The reference instance of <code>jooq</code>
     */
    public static final Jooq JOOQ = new Jooq();

    /**
     * The table <code>jooq.author</code>.
     */
    public final Author AUTHOR = com.ethan.generator.tables.Author.AUTHOR;

    /**
     * The table <code>jooq.book</code>.
     */
    public final Book BOOK = com.ethan.generator.tables.Book.BOOK;

    /**
     * The table <code>jooq.book_store</code>.
     */
    public final BookStore BOOK_STORE = com.ethan.generator.tables.BookStore.BOOK_STORE;

    /**
     * The table <code>jooq.book_to_book_store</code>.
     */
    public final BookToBookStore BOOK_TO_BOOK_STORE = com.ethan.generator.tables.BookToBookStore.BOOK_TO_BOOK_STORE;

    /**
     * The table <code>jooq.language</code>.
     */
    public final Language LANGUAGE = com.ethan.generator.tables.Language.LANGUAGE;

    /**
     * The table <code>jooq.t_department</code>.
     */
    public final Department T_DEPARTMENT = com.ethan.generator.tables.Department.T_DEPARTMENT;

    /**
     * The table <code>jooq.user</code>.
     */
    public final User USER = com.ethan.generator.tables.User.USER;

    /**
     * No further instances allowed
     */
    private Jooq() {
        super("jooq", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            Author.AUTHOR,
            Book.BOOK,
            BookStore.BOOK_STORE,
            BookToBookStore.BOOK_TO_BOOK_STORE,
            Language.LANGUAGE,
            Department.T_DEPARTMENT,
            User.USER);
    }
}
