/*
 * This file is generated by jOOQ.
 */
package com.ethan.generator.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class User implements Serializable {

    private static final long serialVersionUID = -1259624351;

    private Long          id;
    private String        name;
    private String        phone;
    private LocalDateTime createAt;

    public User() {}

    public User(User value) {
        this.id = value.id;
        this.name = value.name;
        this.phone = value.phone;
        this.createAt = value.createAt;
    }

    public User(
        Long          id,
        String        name,
        String        phone,
        LocalDateTime createAt
    ) {
        this.id = id;
        this.name = name;
        this.phone = phone;
        this.createAt = createAt;
    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getPhone() {
        return this.phone;
    }

    public void setPhone(String phone) {
        this.phone = phone;
    }

    public LocalDateTime getCreateAt() {
        return this.createAt;
    }

    public void setCreateAt(LocalDateTime createAt) {
        this.createAt = createAt;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("User (");

        sb.append(id);
        sb.append(", ").append(name);
        sb.append(", ").append(phone);
        sb.append(", ").append(createAt);

        sb.append(")");
        return sb.toString();
    }
}
